### PR TITLE
Fix: notices not displaying properly

### LINKED ISSUE #59: Notices are not displaying properly
I noticed a display issue where the notice appears incorrectly, with raw HTML being printed instead of rendered.

### PR DESCRIPTION
**Pull request by alexmigf**
closes #59

### CODE REVIEW

File: wp-menu-cart.php [hunk 1]
```diff
@@ -295,8 +294,7 @@ public function need_shop() {
 
 	public function woocommerce_version_active() {
 		$error = __( 'An old version of Menu Cart for WooCommerce is currently activated, you need to disable or uninstall it for WP Menu Cart to function properly' , 'wp-menu-cart' );
-		$message = '<div class="error"><p>' . $error . '</p></div>';
-		echo wp_kses_post( $message );
+		printf( '<div class="error"><p>%s</p></div>', $error );
```
Comment (MohamadNateqi) [inline wp-menu-cart.php:297]: Should it be `notice notice-error`?

**Review by MohamadNateqi — APPROVED** [review]
LGTM!
