### PR TITLE
Fix jQuery deprecation warnings

### LINKED ISSUE #14: Fix jQuery deprecation warnings

### PR DESCRIPTION
**Pull request by dpeyou**
closes #14

### CODE REVIEW

File: includes/wpmenucart-settings.php [hunk 1]
```diff
@@ -390,11 +390,11 @@ public function wpmenucart_options_do_page() {
 
 			</form>
 			<script type="text/javascript">
-			jQuery('.hidden-input').click(function() {
+			jQuery('.hidden-input').on('click', function() {
```
Comment (Spreeuw) [inline includes/wpmenucart-settings.php:393]: This part of the code could use a bit of a makeover similar to what I suggested here:
https://github.com/wpovernight/woocommerce-improved-external-products/issues/2#issuecomment-815171252
(the repeated use of `jQuery` is unnecessary and those event triggers should ideally wait for jQuery to be loaded for sure)

**Review by Spreeuw — CHANGES_REQUESTED** [review]

File: includes/wpmenucart-settings.php (hunk 1 above)
Comment (dpeyou) [reply includes/wpmenucart-settings.php]: Like this? https://github.com/wpovernight/wp-menu-cart/pull/15/commits/a79ea5ad82f198c9a639c4cd87ba6aef4b795d74

**Review by Spreeuw — APPROVED** [review]
